apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wisecow
  name: wisecow
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: wisecow
    
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - image: seenumadhavanr/wisecow
          name: wisecow
          ports:
            - containerPort: 4499
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
          livenessProbe:
            tcpSocket:
              port: 4499
            initialDelaySeconds: 8
            periodSeconds: 8
          readinessProbe:
            tcpSocket:
              port: 4499
            initialDelaySeconds: 5
            periodSeconds: 8
